#!/usr/bin/env bash

# Developed by matthew-notaro, nalinahuja22, and ClarkChan1

'''

mazeru --audio-file [FILE] --video-path [PATH] --min-frt [FRAMES] --max-frt [FRAMES]

'''

command python3 ./bin/main.py ${@}
