#!/usr/bin/env bash

# Developed by matthew-notaro, nalinahuja22, and ClarkChan1

# mazeru [AUDIO_FILE] [VIDEO_PATH] [OUTPUT_PATH] --min-sec [SECONDS] --max-sec [SECONDS]

# command python3 ./bin/main.py ${@}

command python3 ./bin/main.py ./media/audio/${1}.wav ./media/video/${2} ./renders/${3}.mp4 --min-sec 2
